module.exports = {
  someSidebar: {
    "Los geht's": ["getting-started", "general", "common-features"],
    Account: ["account-register", "account-login"],
    Apps: [
      "admin",
      "audit-management",
      "blog",
      "crm",
      "document-management",
      "forms",
      "idea-management",
      "maintenance-management",
      "employees",
      "projects-and-tasks",
      "claim-management",
      "opportunity-management",
      "talent-manager",
      "wiki",
      "goal-management",
      "dashboard",
    ],
    FAQs: ["faqs/smartViews", "faqs/supported-browsers"],
    "Technical Documentation (en)": ["installation"],
    Intern: ["tutorial-template", "doc1", "doc2", "doc3", "mdx"],
  },
};
