matrix:
  - name: Markdown
    aspell:
      lang: de
      d: de_DE
    dictionary:
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
    sources:
      - "**/*.md"
    default_encoding: utf-8